---
title: "Reorganize CDL/NVC Match Table"
author: "Melanie Kammerer"
date: "1/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Extract CDL classes that match each NVC
```{r extract}
library(dplyr)
match_table <- read.csv('./data/TabularData/CDL_NVC_AgClassMatch.csv')

levels1 <- sort(unique(match_table$NVC_Match1))
levels1 <- levels1[levels1 != ""]

levels2 <- sort(unique(match_table$NVC_Match2))
levels2 <- levels2[levels2 != ""]

levels3 <- sort(unique(match_table$NVC_Match3))
levels3 <- levels3[levels3 != ""]

levels4 <- sort(unique(match_table$NVC_Match4))
levels4 <- levels4[levels4 != ""]

# level1 column
for (i in 1:length(levels1)) {
  a <- dplyr::filter(match_table, NVC_Match1 == levels1[i]) %>%
  dplyr::select(CLASS_NAME)

  reorg <- data.frame(NVC = levels1[i], CDL_Match=a$CLASS_NAME)
  
  if (i == 1){
    reorg1 <- reorg
  } else if (i > 1) {
    reorg1 <- rbind(reorg1, reorg)
  }
}

# level2 column
for (i in 1:length(levels2)) {
  a <- dplyr::filter(match_table, NVC_Match2 == levels2[i]) %>%
  dplyr::select(CLASS_NAME)

  reorg <- data.frame(NVC = levels2[i], CDL_Match=a$CLASS_NAME)
  
  if (i == 1){
    reorg2 <- reorg
  } else if (i > 1) {
    reorg2 <- rbind(reorg2, reorg)
  }
}

# level3 column
for (i in 1:length(levels3)) {
  a <- dplyr::filter(match_table, NVC_Match3 == levels3[i]) %>%
    dplyr::select(CLASS_NAME)
  
  reorg <- data.frame(NVC = levels3[i], CDL_Match=a$CLASS_NAME)
  
  if (i == 1){
    reorg3 <- reorg
  } else if (i > 1) {
    reorg3 <- rbind(reorg3, reorg)
  }
}

# level4 column
for (i in 1:length(levels4)) {
  a <- dplyr::filter(match_table, NVC_Match4 == levels4[i]) %>%
    dplyr::select(CLASS_NAME)
  
  reorg <- data.frame(NVC = levels4[i], CDL_Match=a$CLASS_NAME)
  
  if (i == 1){
    reorg4 <- reorg
  } else if (i > 1) {
    reorg4 <- rbind(reorg4, reorg)
  }
}

```

## Join together results and format

```{r format}
reorg_all <- rbind(reorg1, reorg2, reorg3, reorg4)

reorg_wide <- dplyr::arrange(reorg_all, CDL_Match) %>% tidyr::pivot_wider(id_cols=NVC, names_from=CDL_Match, values_from=CDL_Match)

reorg_toview <- dplyr::select(reorg_wide, -NVC) %>%
  tidyr::unite(col='CDL_Match_Classes', sep=", ", remove=T, na.rm=T) %>%
  dplyr::mutate(NVC=reorg_wide$NVC) %>%
  dplyr::select(NVC, everything())

```

## Look at output table
```{r table}
library(pander)
pander::pandoc.table(reorg_toview, split.cells = c(15, 45))

```