---
title: "Technical Validation Plots"
author: "Melanie Kammerer"
date: "10/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

## Plots of technical validation results

```{r tabulate_validation}
library(dplyr); library(ggplot2)

# read LANDFIRE and CDL keys
lf_key <- read.csv('D:/SpatialData/LandFire/US_200NVC/CSV_Data/LF_200NVC_05142020.csv')
cdl_key <- read.csv('D:/SpatialData/NASS_CDL/NASS_classes_simple.csv')
states1 <- sf::st_read('D:/SpatialData/state_boundaries/cb_2016_us_state_500k.shp') 

freq <- read.csv('./data/TechnicalValidation/Mismatched_Cells.csv') %>%
  dplyr::select(-X) %>%
  dplyr::left_join(cdl_key, by=c('CDL_Class' = 'VALUE')) %>%
  dplyr::rename(CDL_Name = CLASS_NAME) %>%
  dplyr::left_join(dplyr::select(lf_key, VALUE, NVC_Name), by=c('NVC_Class' = 'VALUE')) %>%
  tidyr::separate(NVC_Name, sep=" ", into=c("Region", "Temperature", "Biome", "NVC_SpecificClass"), remove=F, extra='merge')


#all <- data.table::fread('./data/TechnicalValidation/Mismatch_ByCell.csv') # this file is not updated from Atlas. # it is too large to version control. 


##### load data on # nvc pixels per class per state
nvc_per_state <- read.csv('./data/NVC_StatePixelFreq.csv') %>%
  dplyr::select(-X) %>%
  dplyr::left_join(dplyr::select(states1, STUSPS, NAME), by = c('State'='NAME')) %>%
  dplyr::select(-geometry) %>%
  dplyr::rename(NCells_Class = NCells) %>%
  dplyr::left_join(dplyr::select(lf_key, VALUE, NVC_Name), by= c('NVC_Class'= 'VALUE')) %>% # add landfire class names
  dplyr::filter(NVC_Class %in% freq$NVC_Class) %>% # filter to only agriculture classes
  tidyr::separate(NVC_Name, sep=" ", into=c("Region", "Temperature", "Biome", "NVC_SpecificClass"), remove=F, extra='merge') %>% # create grouped NVC name (removes east/west and warm/cool designations)
  dplyr::group_by(NVC_SpecificClass, State, STUSPS) %>%
  dplyr::summarise(NCells_Class= sum(NCells_Class)) %>%
  dplyr::ungroup()

# summarize number of cells in each NVC grouping nationally (exclude region and temperature)
nvc_national <- dplyr::group_by(nvc_per_state, NVC_SpecificClass) %>%
    dplyr::summarise(NCells_Class= sum(NCells_Class))


##### summarize mis-matched pixels by cdl-nvc pairs & state
cdl_nvc_bystate <- dplyr::group_by(freq, CDL_Class, CDL_Name, NVC_SpecificClass, CDLYear, State) %>%
  dplyr::summarise(NCells_Mismatch = sum(Mismatch_NCells)) %>%
  dplyr::ungroup() %>%
  left_join(dplyr::select(nvc_per_state, NVC_SpecificClass, NCells_Class, STUSPS), by=c('NVC_SpecificClass', 'State'='STUSPS')) %>%
  dplyr::mutate(CDL_Class = as.factor(CDL_Class), NVC_CDL_Named=paste0(NVC_SpecificClass, "_", CDL_Name)) %>%
  dplyr::mutate(Pct_Mismatch = (NCells_Mismatch/NCells_Class)*100)


##### summarize mis-matched pixels by cdl-nvc pairs for entire country
cdl_nvc_national_byYear <- dplyr::group_by(freq, CDL_Class, CDL_Name, NVC_SpecificClass, CDLYear) %>%
  dplyr::summarise(NCells_Mismatch = sum(Mismatch_NCells)) %>%
  dplyr::ungroup() %>%
  left_join(nvc_national) %>%
  dplyr::mutate(CDL_Class = as.factor(CDL_Class), NVC_CDL_Named=paste0(NVC_SpecificClass, "_", CDL_Name)) %>%
  dplyr::mutate(Pct_Mismatch = (NCells_Mismatch/NCells_Class)*100)


cdl_nvc_national_byYear <- dplyr::group_by(cdl_nvc_national_byYear, NVC_SpecificClass, CDLYear) %>%
  dplyr::mutate(CDL_PctPct = Pct_Mismatch/sum(Pct_Mismatch), CDL_PctN = NCells_Mismatch/sum(NCells_Mismatch))

# make variant of CDL names with fewer classes
cdl_nvc_national_byYear$CDL_Name_Pct <- if_else(cdl_nvc_national_byYear$CDL_PctPct < 0.1, 'Other', cdl_nvc_national_byYear$CDL_Name)

cdl_nvc_national_byYear$CDL_Name_N <- if_else(cdl_nvc_national_byYear$CDL_PctN < 0.1, 'Other', cdl_nvc_national_byYear$CDL_Name)
```

## Plot nvc group-cdl mismatch over time
```{r graphs, fig.width=10, fig.height=9}
# colors

cols <- c("#52ef99", "#83366b", "#7ed4d8", "#2c457d", "#63e118", "#621da6", "#bbe272", "#ef66f0", "#155126", "#ff6b97", "#2f937a", "#f24219", "#709f0f", "#1288da", "#e9b7e3", "#8270f6", "#f8d147", "#783019", "#fd8f2f", "#4f462f", "#BEBEBE", "#808080", "#151515")

# percent mis-match
cdl_nvc_national_byYear %>%
ggplot() + geom_bar(aes(x=NVC_SpecificClass, y=Pct_Mismatch, fill=CDL_Name_Pct), 
                    position="stack", stat="identity") +
  theme_classic(base_size=14) +
  ylab('Percent mis-matched pixels') +
  xlab('NVC Class (grouped)') +
  #theme(axis.text.x = element_text(angle = 90)) +
  coord_flip() +
  theme(legend.position="bottom") +
  guides(fill=guide_legend(nrow=8,byrow=TRUE)) +
  facet_wrap(~CDLYear) +
  scale_fill_manual(values= cols, name='CDL Class')

# n mis-matched cells
cdl_nvc_national_byYear %>%
ggplot() + geom_bar(aes(x=NVC_SpecificClass, y=NCells_Mismatch, fill=CDL_Name_N), 
                    position="stack", stat="identity") +
  theme_classic(base_size=14) +
  ylab('Number of mis-matched pixels') +
  xlab('NVC Class (grouped)') +
  #theme(axis.text.x = element_text(angle = 90)) +
  coord_flip() +
  theme(legend.position="bottom") +
  guides(fill=guide_legend(nrow=8,byrow=TRUE)) +
  facet_wrap(~CDLYear) +
  scale_fill_manual(values=cols, name='CDL Class')
```

```{r graphs2, fig.width=5.5, fig.height=4}

year <- dplyr::group_by(freq, CDLYear) %>%
  dplyr::summarise(NCells = sum(Mismatch_NCells)) %>%
  dplyr::mutate(CDLYear = as.factor(CDLYear))

ggplot(data=year) + geom_bar(aes(x=CDLYear, y=NCells), stat="identity") +
  theme_classic(base_size=14) +
  ylab('Number of mis-matched pixels')

# region and temperature
region <- dplyr::group_by(freq, Region, Temperature) %>%
  dplyr::summarise(NCells = sum(Mismatch_NCells))

ggplot(data=region) + geom_bar(aes(x=Region, y=NCells, fill=Temperature), stat="identity") +
  theme_classic(base_size=14) +
  ylab('Number of mis-matched pixels')

```

## Plot nvc group-cdl mismatch over space
```{r map, fig.width=12, fig.height=7}
library(ggplot2); library(viridis)
load('../PollinatorVegetation/data/SpatialData/politicalLL.RDA')
states1 <- sf::st_read('D:/SpatialData/state_boundaries/cb_2016_us_state_500k.shp') %>%
  sf::st_drop_geometry()

states_bc <- sf::st_as_sf(states) %>%
  dplyr::left_join( dplyr::select(states1, STUSPS, NAME), by=c('STATE'='NAME'))
  
# combine all nvc-cdl pairings to map total mis-matched cells per state
testyear <- dplyr::filter(cdl_nvc_bystate) %>%
  dplyr::group_by(State, CDLYear) %>%
  dplyr::summarise(NCells_Mismatch = sum(NCells_Mismatch))

nvc_ncells <- dplyr::group_by(nvc_per_state, State, STUSPS) %>%
  dplyr::summarise(NCells = sum(NCells_Class))

toplot <- dplyr::left_join(states_bc, testyear, by=c('STUSPS'='State')) %>%
  dplyr::left_join(nvc_ncells) %>%
  dplyr::mutate(Pct_Mismatch = NCells_Mismatch/NCells)

##### Total number of mis-matched cells (by state)
ncells_map <- ggplot() + geom_sf(data=toplot, aes(fill=NCells_Mismatch)) +  
  guides(fill=guide_legend(title='Number of \nmis-matched pixels')) +
  theme_classic() + 
  scale_fill_viridis(n.breaks=6) +
  facet_wrap(~CDLYear)
ncells_map


#toplot$Pct_Mismatch <- toplot$Pct_Mismatch*100

##### Percent mis-matched cells (by state)
library(classInt)

min = min(toplot$Pct_Mismatch)
max = max(toplot$Pct_Mismatch)
diff <- max - min
std = sd(toplot$Pct_Mismatch)

equal.interval = seq(min, max, by = diff/8)
quantile.interval = quantile(toplot$Pct_Mismatch, probs=seq(0, 1, by = 1/6))
std.interval = c(seq(min, max, by=std), max)
natural.interval = classIntervals(toplot$Pct_Mismatch, n = 6, style = 'jenks')$brks

toplot$population.equal = cut(toplot$Pct_Mismatch, breaks=equal.interval, include.lowest = TRUE)
toplot$population.quantile = cut(toplot$Pct_Mismatch, breaks=quantile.interval, include.lowest = TRUE)
toplot$population.std = cut(toplot$Pct_Mismatch, breaks=std.interval, include.lowest = TRUE)
toplot$population.natural = cut(toplot$Pct_Mismatch, breaks=natural.interval, include.lowest = TRUE)

pct_map <- ggplot() + geom_sf(data=toplot, aes(fill=Pct_Mismatch)) +  
  guides(fill=guide_legend(title='Percent mis-matched \npixels')) +
  theme_classic() + 
  scale_fill_viridis(n.breaks=6) +
  facet_wrap(~CDLYear)
pct_map

pct_map_equal <- ggplot() + geom_sf(data=toplot, aes(fill=population.equal)) +  
  guides(fill=guide_legend(title='Percent mis-matched \npixels')) +
  theme_classic() + 
  scale_fill_viridis(discrete=T) +
  facet_wrap(~CDLYear)
pct_map_equal

pct_map_quan <- ggplot() + geom_sf(data=toplot, aes(fill=population.quantile)) +  
  guides(fill=guide_legend(title='Percent mis-matched \npixels')) +
  theme_classic() + 
  scale_fill_viridis(discrete=T) +
  facet_wrap(~CDLYear)
pct_map_quan

pct_map_std <- ggplot() + geom_sf(data=toplot, aes(fill=population.std)) +  
  guides(fill=guide_legend(title='Percent mis-matched \npixels')) +
  theme_classic() + 
  scale_fill_viridis(discrete=T) +
  facet_wrap(~CDLYear)
pct_map_std

pct_map_jenks <- ggplot() + geom_sf(data=toplot, aes(fill=population.natural)) +  
  guides(fill=guide_legend(title='Percent mis-matched \npixels')) +
  theme_classic() + 
  scale_fill_viridis(discrete=T) +
  facet_wrap(~CDLYear)
pct_map_jenks

```
```{r hist, fig.width=8, fig.height=7}

eq_hist <- ggplot(toplot, aes(x=Pct_Mismatch))  + geom_histogram(bins=40) + geom_vline(xintercept=equal.interval, col='blue') +
  theme_classic(base_size = 14) +
  ggtitle('Equal-interval breaks')

quan_hist <- ggplot(toplot, aes(x=Pct_Mismatch))  + geom_histogram(bins=40) + geom_vline(xintercept=quantile.interval, col='blue') +
  theme_classic(base_size = 14) +
  ggtitle('Quantile breaks')

std_hist <- ggplot(toplot, aes(x=Pct_Mismatch))  + geom_histogram(bins=40) + geom_vline(xintercept=std.interval, col='blue') +
  theme_classic(base_size = 14) +
  ggtitle('Standard deviation breaks')

jenks_hist <- ggplot(toplot, aes(x=Pct_Mismatch))  + geom_histogram(bins=40) + geom_vline(xintercept=natural.interval, col='blue') +
  theme_classic(base_size = 14) +
  ggtitle('Jenks natural breaks')

library(gridExtra)

grid.arrange(eq_hist, quan_hist, std_hist, jenks_hist, ncol=2)
```
