---
title: "Technical Validation Plots"
author: "Melanie Kammerer"
date: "4/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

## Plots of technical validation results

```{r tabulate_validation}
library(dplyr); library(ggplot2)
nprocess <- 'all'
increment <- 10270
#increment <- 2054
parallel <- T

if (parallel == T) {
  ptext <- 'parallel'
} else {
  ptext <- 'notparallel'
}

# read LANDFIRE and CDL keys
lf_key <- read.csv('../../SpatialData/LandFire/US_200NVC/CSV_Data/LF_200NVC_05142020.csv')
cdl_key <- read.csv('../../SpatialData/NASS_CDL/NASS_classes_simple.csv')
states1 <- sf::st_read('../../SpatialData/state_boundaries/cb_2016_us_state_500k.shp') 
counties <- sf::st_read('./data/SpatialData/us_counties_better_coasts.shp') %>%
  dplyr::filter(!is.na(COUNTY))

# read dataset of number of mis-matched pixels by county
# join with information on CDL and NVC classes
freq <- read.csv(paste0('./data/TechnicalValidation/run', nprocess, '/Mismatched_Cells_byCounty_run', 
    nprocess, '_group', increment, '_' , ptext, '.csv')) %>%
  dplyr::select(-X, -State) %>% # drop state name because some county FIPS codes and State names do not match (tile from close to state boundary)
  dplyr::filter(!is.na(FIPS)) %>% # filter out FIPS with NA values
  dplyr::left_join(cdl_key, by=c('CDL_Class' = 'VALUE')) %>%
  dplyr::rename(CDL_Name = CLASS_NAME) %>%
  dplyr::left_join(dplyr::select(lf_key, VALUE, NVC_Name), by=c('NVC_Class' = 'VALUE')) %>%
  tidyr::separate(NVC_Name, sep=" ", into=c("Region", "Temperature", "Biome", "NVC_SpecificClass"), 
                  remove=F, extra='merge') %>%
  dplyr::mutate(FIPS=as.factor(stringr::str_pad(FIPS, 5, pad = "0"))) # convert FIPS to factor and add leading zeros to match county shp

byyear <- dplyr::ungroup(freq) %>%
  dplyr::group_by(CDLYear) %>%
  dplyr::summarise(Mismatch_NCells = sum(Mismatch_NCells), NCounties = length(unique(FIPS)))

##### load data on # nvc pixels per class per state
nvc_per_county <- read.csv('./data/PixelFreq/NVC_CountyPixelFreq.csv') %>%
  dplyr::left_join(dplyr::select(counties, STATE, COUNTY, FIPS), by = c('State'='STATE', 'County'='COUNTY')) %>%
  dplyr::select(-geometry) %>%
  dplyr::rename(NCells_Class = NCells) %>%
  dplyr::left_join(dplyr::select(lf_key, VALUE, NVC_Name), by= c('Class'= 'VALUE')) %>% # add landfire class names
  dplyr::filter(Class %in% freq$NVC_Class) %>% # filter to only agriculture classes
  tidyr::separate(NVC_Name, sep=" ", into=c("Region", "Temperature", "Biome", "NVC_SpecificClass"), remove=F, extra='merge') %>% # create grouped NVC name (removes east/west and warm/cool designations)
  dplyr::group_by(NVC_SpecificClass, State, County, FIPS) %>%
  dplyr::summarise(NCells_Class= sum(NCells_Class)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(STUSPS=State, FIPS=as.factor(FIPS))

# summarize number of cells in each NVC grouping nationally (groups exclude region and temperature)
nvc_national <- dplyr::group_by(nvc_per_county, NVC_SpecificClass) %>%
    dplyr::summarise(NCells_Class= sum(NCells_Class))


##### summarize mis-matched pixels by cdl-nvc pairs & county
cdl_nvc_bycounty <- dplyr::group_by(freq, CDL_Class, CDL_Name, NVC_SpecificClass, CDLYear, FIPS) %>%
  dplyr::summarise(NCells_Mismatch = sum(Mismatch_NCells)) %>%
  dplyr::ungroup() %>%
  left_join(dplyr::select(nvc_per_county, NVC_SpecificClass, NCells_Class, STUSPS, FIPS),
            by=c('NVC_SpecificClass', 'FIPS')) %>%
  dplyr::rename(State = STUSPS) %>%
  dplyr::mutate(CDL_Class = as.factor(CDL_Class), NVC_CDL_Named=paste0(NVC_SpecificClass, "_", CDL_Name)) %>%
  dplyr::mutate(Pct_Mismatch = (NCells_Mismatch/NCells_Class)*100)

saveRDS(cdl_nvc_bycounty,'./data/TechnicalValidation/pixel_mismatch_byyear_bycounty.RDS')

##### summarize mis-matched pixels by cdl-nvc pairs for entire country
cdl_nvc_national_byYear <- dplyr::group_by(freq, CDL_Class, CDL_Name, NVC_SpecificClass, CDLYear) %>%
  dplyr::summarise(NCells_Mismatch = sum(Mismatch_NCells)) %>%
  dplyr::ungroup() %>%
  left_join(nvc_national) %>%
  dplyr::mutate(CDL_Class = as.factor(CDL_Class), NVC_CDL_Named=paste0(NVC_SpecificClass, "_", CDL_Name)) %>%
  dplyr::mutate(Pct_Mismatch = (NCells_Mismatch/NCells_Class)*100) %>%
  dplyr::ungroup()

pairs_to_keep <- filter(cdl_nvc_national_byYear, Pct_Mismatch > 2.5 | NCells_Mismatch > 3000000)
length(unique(pairs_to_keep$CDL_Class))

cdl_nvc_national_byYear$CDL_Name_N <- if_else(!cdl_nvc_national_byYear$CDL_Class %in% pairs_to_keep$CDL_Class, 'Other', cdl_nvc_national_byYear$CDL_Name)

# take out row crop- close grown crop for visualization
cdl_nvc_national_byYear <- dplyr::filter(cdl_nvc_national_byYear, NVC_SpecificClass != "Row Crop - Close Grown Crop")

```

## Plot nvc group-cdl mismatch over time
```{r graphs, fig.width=12, fig.height=14}
# colors
# cols <- c("#aee39a", "#26496d", "#4cf185", "#D3D3D3", "#77c4d3", "#1c5e39", "#bce333", "#572b9e", "#8699ee", "#9f0b64", "#f597fa", "#6c3357", "#6e9d50")

# try on same graph
var.labs <- c('Number of mismatched pixels', 'Percent mismatched pixels')
names(var.labs) <- c("NCells_Mismatch", "Pct_Mismatch")

la <- tidyr::pivot_longer(cdl_nvc_national_byYear, cols=c(NCells_Mismatch, Pct_Mismatch), names_to='variable_type')
saveRDS(la, './data/summary_pct_mismatch_la.RDS')

# save CDL names (to match with CDL color scheme)
other <- data.frame(CLASS_NAME = 'Other', hex = "#8699ee") # save color code for 'Other' class

cdl_classes_smallmap <- read.csv(paste0('./data/TabularData/NASS_classes_pasture_is_arable.csv')) %>% 
  dplyr::mutate(VALUE = as.character(-VALUE)) %>%
  dplyr::select(VALUE, CLASS_NAME, RED, GREEN, BLUE) %>%
  dplyr::filter(CLASS_NAME %in% la$CDL_Name_N) %>%
  dplyr::mutate(hex = rgb(RED, GREEN, BLUE)) %>%
  dplyr::full_join(other) %>%
  dplyr::arrange(CLASS_NAME)

cols <- cdl_classes_smallmap$hex

combined <- la %>% ggplot() + geom_bar(aes(x=NVC_SpecificClass, y=value, 
                                           fill=stringr::str_wrap(CDL_Name_N, width=12)), 
                    position="stack", stat="identity") +
  ylab('') +
  xlab('NVC agriculture classes (grouped)') +
  coord_flip() +
  guides(fill=guide_legend(ncol=1, byrow=T)) +
  facet_grid(CDLYear~variable_type, scales='free', labeller = labeller(variable_type=var.labs)) +
  scale_fill_manual(values=cols, name='CDL Class') +
  theme_classic(base_size=14) +
  theme(legend.spacing.y = unit(0.2, "cm"),
       panel.border = element_rect(fill = NA, color = "black"),
       #panel.background = element_blank(), 
       #panel.grid = element_blank(), 
       panel.spacing.x = unit(0,"line"),
       panel.spacing.y = unit(0,"line"))

combined
ggplot2::ggsave(plot=combined, './figures/TechnicalValidation_current/MismatchedPixels_2012_to_2021.pdf', width=12, height=14)
```

## Plot nvc group-cdl mismatch over space
```{r map, fig.width=10, fig.height=12}
library(ggplot2); library(viridis)
  
# combine all nvc-cdl pairings to map total mis-matched cells per county
testyear <- cdl_nvc_bycounty %>%
  dplyr::group_by(State, FIPS, CDLYear) %>%
  dplyr::summarise(NCells_Mismatch = sum(NCells_Mismatch))

allcounties <- counties %>%
  dplyr::mutate(FIPS = as.factor(FIPS)) %>%
  dplyr::full_join(dplyr::ungroup(testyear)) %>%
  tidyr::replace_na(list(CDLYear=2012)) %>%
  tidyr::expand(FIPS, CDLYear)

nvc_ncells <- dplyr::group_by(nvc_per_county, State, FIPS) %>%
  dplyr::summarise(NCells = sum(NCells_Class, na.rm=T))


toplot <- counties %>%
  dplyr::mutate(FIPS = as.factor(FIPS)) %>%
  dplyr::full_join(dplyr::select(nvc_ncells, FIPS, NCells)) %>%
  dplyr::full_join(allcounties) %>%
  dplyr::full_join(testyear) %>%
  tidyr::replace_na(list(NCells_Mismatch=0, NCells=1)) %>% # if NA value for NCells_Mismatch, assume no mismatched pixels for that year-county combo
  # set NCells = NA to 1 to avoid divide by zero error
  dplyr::mutate(Pct_Mismatch = (NCells_Mismatch/NCells)*100)

saveRDS(toplot, './data/summary_pct_mismatch_toplot.RDS')


# identify counties with the highest percent mismatch
worst_counties <- dplyr::filter(toplot, CDLYear == 2017) %>%
  dplyr::arrange(desc(Pct_Mismatch)) %>%
  dplyr::filter(NCells_Mismatch > 100, Pct_Mismatch > 65)

# save data frame for the worst mismatched counties in 2017
saveRDS(worst_counties, './data/TechnicalValidation/counties_with_highest_mismatch_2017.rds')

library(classInt); library(viridis)

##### Percent mis-matched cells (by county)
natural.interval = classIntervals(toplot$Pct_Mismatch, n = 6, style = 'jenks')$brks
toplot$population.natural = cut(toplot$Pct_Mismatch, breaks=natural.interval, include.lowest = TRUE)

pct_map_jenks <- toplot %>%
  sf::st_transform("ESRI:102003") %>%
  ggplot() + geom_sf(aes(fill=population.natural), color=NA) +  
  guides(fill=guide_legend(title='Percent NVC agriculture\nmismatched with CDL')) +
  theme_minimal() + 
  scale_fill_viridis(discrete=T) +
  facet_wrap(~CDLYear, ncol=2)
pct_map_jenks
ggplot2::ggsave(plot=pct_map_jenks, './figures/TechnicalValidation_current/MismatchedPixelsMap_ByCounty_2012_to_2021.pdf', width=10, height=12)

```

```{r oneyear, fig.width=10, fig.height=5}
map2017 <- dplyr::filter(toplot, CDLYear == 2017) %>%
  sf::st_transform("ESRI:102003") %>%
  ggplot() + geom_sf(aes(fill=population.natural), color=NA) +  
  guides(fill=guide_legend(title='Percent NVC agriculture\nmismatched with CDL')) +
  theme_minimal(base_size=13) + 
  scale_fill_viridis(discrete=T, option='viridis') +
  theme(legend.position=c(1.02,0.25))
map2017 

byclass_2017 <- dplyr::filter(la, CDLYear == 2017) %>% 
  ggplot() + geom_col(aes(x=stringr::str_wrap(NVC_SpecificClass, width=12), y=value, 
  fill=stringr::str_wrap(CDL_Name_N, width=12), width=0.85), 
  position="stack", stat="identity") +
  ylab('') +
  xlab('NVC agriculture classes (grouped)') +
  coord_flip() +
  guides(fill=guide_legend(nrow=2, byrow=T, reverse=T)) +
  facet_grid(~variable_type, scales='free', labeller = labeller(variable_type=var.labs)) +
  scale_fill_manual(values=cols, name='CDL\nClass') +
  theme_classic(base_size=14) +
  theme(legend.spacing.y = unit(0.05, "cm"),
        legend.spacing.x = unit(0.15, "cm"),
        # panel.border = element_rect(fill = NA, color = "black"),
        panel.spacing.x = unit(0,"line"),
        panel.spacing.y = unit(0,"line"),
        legend.position = 'bottom', 
        legend.justification = 'left',
        strip.text.x = element_text(size = 14))

byclass_2017 
```

```{r oneyear_multi, fig.width=10, fig.height=11}
library(cowplot); library(gridExtra)

seventeen <- ggdraw() +
  draw_plot(byclass_2017, x=0, y=0.5, 1, 0.48) +
  draw_plot(map2017, x=0.01, y=0.05, 1, 0.425)

seventeen

# ggplot2::ggsave(plot=seventeen, paste0('./figures/TechnicalValidation_current/CombinedFigMap_MismatchedPixels_', CDLYear, 'Only.pdf'), width=10, height=11)

```

```{r oneyear_multi3, fig.width=10, fig.height=15}
library(cowplot); library(gridExtra)
CDLYear <- 2017
# read ggplot object generated in 'WrangleMergedAccuracyByCounty.Rmd'
nodata_map_jenks <- readRDS(paste0('./data/nodata_map_jenks_CDL', CDLYear, '.rds'))

seventeen3 <- ggdraw() +
  draw_plot(byclass_2017, x=0, y=0.63, 1, 0.325) +
  draw_plot(map2017, x=0.01, y=0.3, 1, 0.32) +
  draw_plot(nodata_map_jenks, x=0.01, y=0, 1, 0.32) +
  annotate("text", label="(a)", x=0.06, y=0.94, size=7) +
  annotate("text", label="(b)", x=0.06, y=0.605, size=7) +
  annotate("text", label="(c)", x=0.06, y=0.305, size=7)


seventeen3

ggplot2::ggsave(plot=seventeen3, paste0('./figures/TechnicalValidation_current/Fig2_CombinedFigMap3Panel_MismatchedPixels_', CDLYear, 'Only.pdf'),
                width=10, height=15)
```




